class ItemsAddWineForm {

  static const List<String> tipos = [
    'Tinto, Joven',
    'Tinto, Maceración Carbónica',
    'Tinto, Roble',
    'Tinto, con Crianza',
    'Tinto, Crianza',
    'Tinto, Reserva',
    'Tinto, Gran Reserva',
    'Blanco, Joven',
    'Blanco, Fermentado en barrica',
    'Blanco, con Crianza',
    'Espumoso, Cava',
    'Espumoso, Cava de guarda',
    'Espumoso, Cava de guarda Superior',
    'Espumoso, Cava Reserva',
    'Espumoso, Cava Gran Reserva',
    'Espumoso, Cava de Paraje Calificado',
    'Espumoso, Corpinnat',
    'Espumoso, Corpinnat Reserva',
    'Espumoso, Corpinnat Gran Reserva',
    'Espumoso, Champan',
    'Espumoso, de Aguja',
    'Espumoso, Espumoso',
  ];

  static const List<String> region = <String>[
    'Abadía Retuerta (D.O.)',
    'Abona (D.O.)',
    'Alella (D.O.)',
    'Alicante (D.O.)',
    'Almansa (D.O.)',
    'Arlanza (D.O.)',
    'Arribes (D.O.)',
    'Bierzo (D.O.)',
    'Binissalem (D.O.)',
    'Bolandin (D.O.)',
    'Bullas (D.O.)',
    'Calatayud (D.O.)',
    'Campo de Borja (D.O.)',
    'Cariñena (D.O.)',
    'Catalunya (D.O.)',
    'Cava (D.O.)',
    'Cigales (D.O.)',
    'Conca de Barberá (D.O.)',
    'Condado de Huelva (D.O.)',
    'Costers del Segre (D.O.)',
    'Dehesa Peñalba (D.O.)',
    'El Hierro (D.O.)',
    'Empordá (D.O.)',
    'Gran Canaria (D.O.)',
    'Granada (D.O.)',
    'Jerez-Xérès-Sherry (D.O.)',
    'Jumilla (D.O.)',
    'La Gomera (D.O.)',
    'La Mancha (D.O.)',
    'La Palma (D.O.)',
    'Lanzarote (D.O.)',
    'León (D.O.)',
    'Málaga (D.O.)',
    'Manchuela (D.O.)',
    'Manzanilla-Sanlúcar de Barrameda (D.O.)',
    'Méntrida (D.O.)',
    'Mondéjar (D.O.)',
    'Monterrei (D.O.)',
    'Montilla-Moriles (D.O.)',
    'Montsant (D.O.)',
    'Navarra (D.O.)',
    'Penedés (D.O.)',
    'Pla de Bages (D.O.)',
    'Pla i Llevant (D.O.)',
    'Rías Baixas (D.O.)',
    'Ribeira Sacra (D.O.)',
    'Ribeiro (D.O.)',
    'Ribera del Duero (D.O.)',
    'Ribera del Guadiana (D.O.)',
    'Ribera del Júcar (D.O.)',
    'Rueda (D.O.)',
    'Sierras de Málaga (D.O.)',
    'Somontano (D.O.)',
    'Tacoronte-Acentejo (D.O.)',
    'Tarragona (D.O.)',
    'Terra Alta (D.O.)',
    'Tierra del Vino de Zamora (D.O.)',
    'Toro (D.O.)',
    'Txakolí de Álava (D.O.)',
    'Txakolí de Bizkaia (D.O.)',
    'Txakolí de Guetaria (D.O.)',
    'Uclés (D.O.)',
    'Urueña (D.O.)',
    'Utiel-Requena (D.O.)',
    'Valdeorras (D.O.)',
    'Valdepeñas (D.O.)',
    'Valencia (D.O.)',
    'Valle de Güímar (D.O.)',
    'Valle de la Orotava (D.O.)',
    'Vinos de Madrid (D.O.)',
    'Ycoden-Daute-Isora (D.O.)',
    'Yecla (D.O.)',
    'Priorat (D.O.Ca.)',
    'Rioja (D.O.Ca.)',
    'Cangas (V.C.)',
    'Cebreros (V.C.)',
    'Islas Canarias (V.C.)',
    'Lebrija (V.C.)',
    'Sierra de Salamanca (V.C.)',
    'Valles de Benavente (V.C.)',
    'Valtienda (V.C.)',
    'Aylés (V.P.)',
    'Calzadilla (V.P.)',
    'Campo de la Guardia (V.P.)',
    'Casa del Blanco (V.P.)',
    'Chozas Carrascal (V.P.)',
    'Dehesa del Carrizal (V.P.)',
    'Dominio de Valdepusa (V.P.)',
    'El Terrerazo (V.P.)',
    'El Vicario (V.P.)',
    'Finca Élez (V.P.)',
    'Guijoso (V.P.)',
    'La Jaraba (V.P.)',
    'Los Balagueses (V.P.)',
    'Los Cerrillos (V.P.)',
    'Pago de Arinzano (V.P.)',
    'Pago de Otazu (V.P.)',
    'Pago Florentino (V.P.)',
    'Prado de Irache (V.P.)',
    'Vallegarcía (V.P.)',
    'Vera de Estenas (V.P.)',
    '3 Riberas (I.G.P.)',
    'Altiplano de Sierra Nevada (I.G.P.)',
    'Bailén (I.G.P.)',
    'Bajo Aragón (I.G.P.)',
    'Barbanza e Iria (I.G.P.)',
    'Betanzos (I.G.P.)',
    'Cádiz (I.G.P.)',
    'Campo de Cartagena (I.G.P.)',
    'Castelló (I.G.P.)',
    'Castilla (I.G.P.)',
    'Castilla y León (I.G.P.)',
    'Córdoba (I.G.P.)',
    'Costa de Cantabria (I.G.P.)',
    'Cumbres del Guadalfeo (I.G.P.)',
    'Desierto de Almería (I.G.P.)',
    'Extremadura (I.G.P.)',
    'Formentera (I.G.P.)',
    'Ibiza (I.G.P.)',
    'Illes Balears (I.G.P.)',
    'Isla de Menorca (I.G.P.)',
    'Laderas del Genil (I.G.P.)',
    'Laujar-Alpujarra (I.G.P.)',
    'Liébana (I.G.P.)',
    'Los Palacios (I.G.P.)',
    'Mallorca (I.G.P.)',
    'Murcia (I.G.P.)',
    'Norte de Almería (I.G.P.)',
    'Ribera do Morrazo (I.G.P.)',
    'Ribera del Andarax (I.G.P.)',
    'Ribera del Gállego-Cinco Villas (I.G.P.)',
    'Ribera del Jiloca (I.G.P.)',
    'Ribera del Queiles (I.G.P.)',
    'Serra de Tramuntana-Costa Nord (I.G.P.)',
    'Sierra Norte de Sevilla (I.G.P.)',
    'Sierra Sur de Jaén (I.G.P.)',
    'Sierras de Las Estancias y Los Filabres (I.G.P.)',
    'Torreperogil (I.G.P.)',
    'Valdejalón (I.G.P.)',
    'Valle del Cinca (I.G.P.)',
    'Valle del Miño-Ourense (I.G.P.)',
    'Valles de Sadacia (I.G.P.)',
    'Villaviciosa de Córdoba (I.G.P.)',
    'Vino de España',
    'Sin D.O.',
    'Otro País',
  ];

  static List<String> anada() {
    final DateTime date = DateTime.now().toUtc();
    final int year = date.year;
    final anada = List.generate(year - 1950, (index) => (year - index).toString());
    return anada;
  }
  
}